{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1729177491333, "stop": 1729177491945, "uuid": "c6804cb6-1d15-4ea3-b4da-9b1218d96e19", "historyId": "fda5b7c211db2d8f7b96e3d91791537f", "testCaseId": "fda5b7c211db2d8f7b96e3d91791537f", "fullName": "test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-I4FH3MC"}, {"name": "thread", "value": "25636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_authentication"}]}