{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1729329580405, "stop": 1729329581080, "uuid": "62a31099-c196-4d54-9bf9-10b9c02c7685", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-I4FH3MC"}, {"name": "thread", "value": "108300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}