{"name": "Проверка ответа на запрос изменения данных неаутентифицированного пользователя", "status": "passed", "start": 1729178521368, "stop": 1729178521826, "uuid": "43622495-bd07-43db-bb90-d0cd6ccf1c05", "historyId": "15ddd7987c2e5999e579e59a038213af", "testCaseId": "15ddd7987c2e5999e579e59a038213af", "fullName": "tests.test_user_update.TestUserUpdate#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-I4FH3MC"}, {"name": "thread", "value": "30280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}